# Generated by Django 3.0.4 on 2020-03-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='DSC_0890.JPG', upload_to='profile_pics'),
        ),
    ]
